using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using System.Windows;

namespace SmakLivery
{
    public static class DbHelper
    {
        //private static string connStr = "Host=localhost;Username=postgres;Password=postgres;Database=smaklivery";
        // Для маппинга ENUM из БД в C# и наоборот
        private static readonly NpgsqlDataSource _ds =
            new NpgsqlDataSourceBuilder("Host=localhost;Username=postgres;Password=postgres;Database=smaklivery")
                .MapEnum<OrderStatus>("order_status") // Маппинг типов!!!
                .Build();
        public static async Task CreateDbAsync()
        {
            var createEnumQuery = @"
                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
                        CREATE TYPE order_status AS ENUM (
                            'accepted',
                            'preparing',
                            'out_for_delivery',
                            'delivered',
                            'cancelled'
                        );
                    END IF;
                END $$;";

            var createTableQuery = @"
                CREATE TABLE IF NOT EXISTS ""order""(
                    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    address VARCHAR(255) NOT NULL,
                    status order_status NOT NULL DEFAULT 'accepted',
                    courier_id BIGINT,
                    PRIMARY KEY (id)
                );";

            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();
            await using var cmd1 = new NpgsqlCommand(createEnumQuery, conn);
                await cmd1.ExecuteNonQueryAsync();

            await using var cmd2 = new NpgsqlCommand(createTableQuery, conn);
                await cmd2.ExecuteNonQueryAsync();
        }

        //private static OrderStatus GetOrderStatusFrom(string statusName)
        //{
        //    return statusName switch
        //    {
        //        "Отменен" => OrderStatus.Cancelled,
        //        "Готовится" => OrderStatus.Prepearing,
        //        "Передан курьеру" => OrderStatus.OutForDelivery,
        //        "Получен" => OrderStatus.Delivered,
        //        _ => OrderStatus.Accepted
        //    };
        //}

        //private static string GetStatusNameFrom(OrderStatus status)
        //{
        //    return status switch
        //    {
        //        OrderStatus.Cancelled => "Отменен",
        //        OrderStatus.Prepearing => "Готовится",
        //        OrderStatus.OutForDelivery => "Передан курьеру",
        //        OrderStatus.Delivered => "Получен",
        //        _ => "Принят"
        //    };
        //}

        public static async Task<List<Order>> GetOrders()
        {
            var orders = new List<Order>();
            var query = "SELECT * FROM \"order\";";
            await using var conn = _ds.CreateConnection();
            await conn.OpenAsync();
            await using var cmd = new NpgsqlCommand(query, conn);
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                orders.Add(new Order()
                {
                    Id = reader.GetInt64(0),
                    Address = reader.GetString(1),
                    Status = reader.GetFieldValue<OrderStatus>(2),
                    CourierId = await reader.IsDBNullAsync(3) ? null : reader.GetInt64(3)
                });
            }
            MessageBox.Show(orders.ToString());
            return orders;
        }
    }
}
